name: DeathPunish
main: com.deathPunish.DeathPunish
version: 1.2.2
api-version: 1.13
commands:
  setmaxhealth:
    #描述这个命令
    description: 设置玩家最大生命值
    #用法
    usage: /deathpunish setmaxhealth <player> <maxhealth> <true/false>
    #执行此命令的人所需的权限
    permission: op
    #没有权限的提示消息
    permission-message: 你没有权限！
  deathpunish:
    #描述这个命令
    description:
    #用法
    usage: /deathpunish
    #执行此命令的人所需的权限
    permission: op
    #没有权限的提示消息
    permission-message: 你没有权限！
  reload:
    #描述这个命令
    description: 重载插件配置
    #用法
    usage: /deathpunish reload
    #执行此命令的人所需的权限
    permission: op
    #没有权限的提示消息
    permission-message: 你没有权限！


