name: DeathPunish
main: com.deathPunish.DeathPunish
version: 1.4.4
api-version: 1.13
folia-supported: true
softdepend: [Vault]

commands:
  deathpunish:
    description: 死亡惩罚
    usage: /deathpunish <help|give|set|add|get|reload>
    aliases:
      - dp

permissions:
  deathpunish.command:
    description: deathpunish command permission
    default: op
  deathpunish.bypass:
    description: deathpunish bypass permission
    default: false
  deathpunish.craft:
    description: 允许制作回血物品
    default: true
  deathpunish.protect:
    description: 允许使用死亡保护物品
    default: true
